### ISSUE TITLE
All slf4s log messages specify "logger.scala:85" as the file/line associated with the log message.

### ISSUE THREAD

**Issue by ghost** [w11k/slf4s#16]
When utilizing the Logging trait with slf4s and logback, all log messages specify logger.scala:85 as the filename and line associated with the log message, i.e.:

010-10-25 10:57:37,307 INFO my.package.MyClass [logger.scala:85] My Log Message

I'd expect this to read MyClass.scala:X rather than logger.scala:85.

**Comment by hseeberger** [comment]
I guess that's because the actual call to org.slf4j.Logger happens in logger.scala. Maybe that's an issue related to the missing marker implementation? If not, there is probably nothing we can do ...

**Comment by mkneissl** [comment]
You have to delegate to LocationAwareLogger.

I've just submitted a pull request for this issue: https://github.com/weiglewilczek/slf4s/pull/22 .

**Comment by mkneissl** [comment]
closed by 7215441ec9c4f66d4d7e0a610c8f288712378b7c: Source location is now reported properly.

For backends that support source location such as class, file, line number, the source of the caller of the slf4s API is now reported instead of the source within the slf4s implementation.

TODO: This change depends on SLF4J API 1.6.x, so probably the SLF4S minor version should be incremented.
