### ISSUE TITLE
accurate line numbers?

### ISSUE THREAD

**Issue by jpswain** [w11k/slf4s#21]
Hi,

Nice project!
I was just wondering if there is a way to get actual line numbers from my scala classes?  Currently my output lists all the same line number, in this case 93, in a class that only has 32 lines.  I assume this is because the line numbers are based on an intermediate step of compilation where it looks like a Java class file.  Is there config change I can do to get around this, or a way to fix it?

Thanks!
Jamie

**Comment by mkneissl** [comment]
See http://stackoverflow.com/questions/4835813/scala-logging-line-numbers-slf4s-slf4j/4835999#4835999 . I'd set -g:vars in the compilation options of the client project.

Reporting of the line numbers has been fixed in response to [issue #16](https://github.com/weiglewilczek/slf4s/issues/closed#issue/16).
